#Chonkie SemanticChunker
Made by: Wilfredo Aaron Sosa Ramos

In [1]:
!pip install -q chonkie[all] "chonkie[semantic]"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.2/51.2 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 29.6 MB/s eta 0:00:00


##Single Text Chunking

In [4]:
from chonkie import SemanticChunker

# Basic initialization with default parameters
chunker = SemanticChunker(
    embedding_model="minishlab/potion-base-8M",  # Default model
    threshold=0.5,                               # Similarity threshold (0-1) or (1-100) or "auto"
    chunk_size=256,                              # Maximum tokens per chunk
    min_sentences=1                              # Initial sentences per chunk
)

In [5]:
text = """
1. The Evolution of LLM Engineering
LLM engineering is a cornerstone of modern artificial intelligence, enabling the development and optimization of large language models for diverse applications. These models, like GPT-4 or Gemini, are trained on massive datasets and possess extraordinary capabilities in natural language understanding and generation. However, their true utility lies in how they are engineered to interact with specific tasks and contexts. LLM engineering focuses on creating robust pipelines, integrating external tools, and refining user interactions to make models more effective, reliable, and adaptable. It also addresses challenges like hallucinations, bias, and efficiency, ensuring that these models deliver meaningful and accurate results across industries such as education, healthcare, and business.

2. The Science of Prompt Design
Central to LLM engineering is the art and science of prompt design—crafting the textual or programmatic inputs that guide the model’s behavior. Prompting techniques range from basic approaches, like zero-shot and few-shot prompting, to more advanced strategies, such as instruction tuning and dynamic prompt engineering. Zero-shot prompting involves giving the model a direct task with minimal context, while few-shot prompting provides examples to improve performance. Engineers often employ techniques like chaining prompts or incorporating contextual constraints to guide the model’s reasoning process. By mastering prompt design, LLM engineers can unlock the model's latent potential, ensuring it understands tasks deeply and produces high-quality outputs.

3. Advanced Prompting Techniques and Applications
Beyond basic prompting, advanced techniques enable LLMs to tackle complex, multi-step tasks effectively. For example, chain-of-thought prompting encourages models to explain their reasoning step by step, improving accuracy in tasks requiring logical deduction. Similarly, self-reflection prompts ask the model to evaluate its own responses, fostering iterative improvements. These techniques are particularly valuable in applications like legal research, scientific analysis, and technical writing, where precision and clarity are paramount. By leveraging such methods, LLM engineers can adapt models to solve intricate problems, making them indispensable tools in high-stakes environments.

4. Integration with External Systems
Another critical aspect of LLM engineering is integrating models with external tools and APIs to expand their functionality. Through techniques like tool usage prompting and plugin development, LLMs can perform tasks beyond text generation, such as retrieving real-time data, running calculations, or interacting with software systems. For example, an LLM integrated with a database API can provide detailed analytics based on structured data queries. This seamless integration transforms LLMs into versatile agents capable of executing end-to-end workflows, enhancing their value in industries like finance, e-commerce, and AI-powered customer support.

5. Ethical Considerations in LLM Engineering
As LLMs become increasingly integrated into society, ethical considerations are a vital component of LLM engineering. Engineers must address issues such as bias, fairness, and privacy to ensure responsible AI deployment. Prompt design plays a significant role in mitigating biases by carefully framing tasks and curating training datasets. Moreover, engineers are tasked with implementing safeguards against misuse, such as restricting harmful outputs or ensuring compliance with data privacy regulations. Ethical LLM engineering not only protects users but also builds trust in AI systems, paving the way for their widespread acceptance and integration.

6. The Future of LLM Engineering and Prompting
The future of LLM engineering lies in the continued refinement of prompting techniques and the development of specialized models tailored to specific industries. Emerging trends include adaptive prompt generation, where AI dynamically modifies prompts based on user behavior, and multi-modal integration, allowing models to process and generate text, images, and other data types seamlessly. Additionally, advancements in reinforcement learning and fine-tuning will enable LLMs to learn from user feedback, improving their performance over time. As the field evolves, LLM engineers and researchers will play a crucial role in shaping AI's impact on society, driving innovation while upholding ethical and technical standards.
"""

chunks = chunker.chunk(text)

for chunk in chunks:
    print(f"Chunk text: {chunk.text}")
    print(f"Token count: {chunk.token_count}")
    print(f"Number of sentences: {len(chunk.sentences)}")

Chunk text: 
1. The Evolution of LLM Engineering
LLM engineering is a cornerstone of modern artificial intelligence, enabling the development and optimization of large language models for diverse applications. These models, like GPT-4 or Gemini, are trained on massive datasets and possess extraordinary capabilities in natural language understanding and generation. However, their true utility lies in how they are engineered to interact with specific tasks and contexts. LLM engineering focuses on creating robust pipelines, integrating external tools, and refining user interactions to make models more effective, reliable, and adaptable. It also addresses challenges like hallucinations, bias, and efficiency, ensuring that these models deliver meaningful and accurate results across industries such as education, healthcare, and business.

2. The Science of Prompt Design
Central to LLM engineering is the art and science of prompt design—crafting the textual or programmatic inputs that guide t

In [6]:
# 1. The Evolution of LLM Engineering
evolution_of_llm_engineering = [
    "LLM engineering is a cornerstone of modern artificial intelligence, enabling the development and optimization of large language models for diverse applications.",
    "These models, like GPT-4 or Gemini, are trained on massive datasets and possess extraordinary capabilities in natural language understanding and generation.",
    "However, their true utility lies in how they are engineered to interact with specific tasks and contexts.",
    "LLM engineering focuses on creating robust pipelines, integrating external tools, and refining user interactions to make models more effective, reliable, and adaptable.",
    "It also addresses challenges like hallucinations, bias, and efficiency, ensuring that these models deliver meaningful and accurate results across industries such as education, healthcare, and business."
]

# 2. The Science of Prompt Design
science_of_prompt_design = [
    "Central to LLM engineering is the art and science of prompt design—crafting the textual or programmatic inputs that guide the model’s behavior.",
    "Prompting techniques range from basic approaches, like zero-shot and few-shot prompting, to more advanced strategies, such as instruction tuning and dynamic prompt engineering.",
    "Zero-shot prompting involves giving the model a direct task with minimal context, while few-shot prompting provides examples to improve performance.",
    "Engineers often employ techniques like chaining prompts or incorporating contextual constraints to guide the model’s reasoning process.",
    "By mastering prompt design, LLM engineers can unlock the model's latent potential, ensuring it understands tasks deeply and produces high-quality outputs."
]

# 3. Advanced Prompting Techniques and Applications
advanced_prompting_techniques = [
    "Beyond basic prompting, advanced techniques enable LLMs to tackle complex, multi-step tasks effectively.",
    "For example, chain-of-thought prompting encourages models to explain their reasoning step by step, improving accuracy in tasks requiring logical deduction.",
    "Similarly, self-reflection prompts ask the model to evaluate its own responses, fostering iterative improvements.",
    "These techniques are particularly valuable in applications like legal research, scientific analysis, and technical writing, where precision and clarity are paramount.",
    "By leveraging such methods, LLM engineers can adapt models to solve intricate problems, making them indispensable tools in high-stakes environments."
]

# 4. Integration with External Systems
integration_with_external_systems = [
    "Another critical aspect of LLM engineering is integrating models with external tools and APIs to expand their functionality.",
    "Through techniques like tool usage prompting and plugin development, LLMs can perform tasks beyond text generation, such as retrieving real-time data, running calculations, or interacting with software systems.",
    "For example, an LLM integrated with a database API can provide detailed analytics based on structured data queries.",
    "This seamless integration transforms LLMs into versatile agents capable of executing end-to-end workflows.",
    "It enhances their value in industries like finance, e-commerce, and AI-powered customer support."
]

# 5. Ethical Considerations in LLM Engineering
ethical_considerations = [
    "As LLMs become increasingly integrated into society, ethical considerations are a vital component of LLM engineering.",
    "Engineers must address issues such as bias, fairness, and privacy to ensure responsible AI deployment.",
    "Prompt design plays a significant role in mitigating biases by carefully framing tasks and curating training datasets.",
    "Moreover, engineers are tasked with implementing safeguards against misuse, such as restricting harmful outputs or ensuring compliance with data privacy regulations.",
    "Ethical LLM engineering not only protects users but also builds trust in AI systems, paving the way for their widespread acceptance and integration."
]

# 6. The Future of LLM Engineering and Prompting
future_of_llm_engineering = [
    "The future of LLM engineering lies in the continued refinement of prompting techniques and the development of specialized models tailored to specific industries.",
    "Emerging trends include adaptive prompt generation, where AI dynamically modifies prompts based on user behavior, and multi-modal integration, allowing models to process and generate text, images, and other data types seamlessly.",
    "Additionally, advancements in reinforcement learning and fine-tuning will enable LLMs to learn from user feedback, improving their performance over time.",
    "As the field evolves, LLM engineers and researchers will play a crucial role in shaping AI's impact on society.",
    "They will drive innovation while upholding ethical and technical standards."
]
texts = evolution_of_llm_engineering + science_of_prompt_design + advanced_prompting_techniques + integration_with_external_systems + ethical_considerations + future_of_llm_engineering

In [7]:
batch_chunks = chunker.chunk_batch(texts)

for doc_chunks in batch_chunks:
    for chunk in doc_chunks:
        print(f"Chunk: {chunk.text}")

🦛 choooooooooooooooooooonk 100% • 30/30 docs chunked [00:00<00:00, 1681.33doc/s] 🌱

Chunk: LLM engineering is a cornerstone of modern artificial intelligence, enabling the development and optimization of large language models for diverse applications.
Chunk: These models, like GPT-4 or Gemini, are trained on massive datasets and possess extraordinary capabilities in natural language understanding and generation.
Chunk: However, their true utility lies in how they are engineered to interact with specific tasks and contexts.
Chunk: LLM engineering focuses on creating robust pipelines, integrating external tools, and refining user interactions to make models more effective, reliable, and adaptable.
Chunk: It also addresses challenges like hallucinations, bias, and efficiency, ensuring that these models deliver meaningful and accurate results across industries such as education, healthcare, and business.
Chunk: Central to LLM engineering is the art and science of prompt design—crafting the textual or programmatic inputs that guide the model’s behavior.
Chunk: Prompting te

#Embeddings

##1. AutoEmbeddings

In [10]:
import os
from google.colab import userdata

os.environ['HF_TOKEN'] = userdata.get('HF_TOKEN')
os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY')

In [12]:
from chonkie import AutoEmbeddings

# Get the embeddings handler for SentenceTransformer
embeddings_sentence_transformer = AutoEmbeddings.get_embeddings("all-MiniLM-L6-v2")

# Get the embeddings handler for OpenAI
embeddings_openai = AutoEmbeddings.get_embeddings("text-embedding-3-large")

# Get the embeddings handler for Model2Vec
embeddings_model2vec = AutoEmbeddings.get_embeddings("minishlab/potion-base-8M")

In [13]:
# Single text embedding
emb_single_text = embeddings_sentence_transformer.embed(text)

# Batch processing
emb_batch_processing = embeddings_sentence_transformer.embed_batch(texts)

# Direct calling
emb_direct_calling = embeddings_sentence_transformer(text)  # or embeddings([text1, text2])

In [14]:
emb_single_text

array([ 2.48870794e-02,  1.83277112e-02,  4.77530658e-02, -1.38475662e-02,
        3.02790962e-02, -4.32046838e-02,  6.23071427e-03,  5.95367439e-02,
       -1.12173532e-03, -4.43947613e-02, -1.33559808e-01, -4.43594046e-02,
        1.11916095e-01, -3.71096767e-02,  2.33589225e-02,  7.19019724e-03,
        9.25967693e-02, -3.25391367e-02, -2.97154281e-02, -4.53184731e-02,
        4.93117049e-02,  4.15870920e-02,  7.90585428e-02,  1.44620230e-02,
       -7.66994208e-02, -1.83139148e-03,  4.59219553e-02, -3.48730391e-04,
        6.43289238e-02, -1.70797128e-02,  3.42165120e-02,  5.80768213e-02,
        1.24822510e-02,  6.57148957e-02, -4.90070283e-02,  4.40610908e-02,
       -2.78278813e-02,  4.24919464e-02, -6.80714706e-03, -5.28121889e-02,
       -8.37868154e-02, -6.89068213e-02,  2.37371586e-02, -2.66803242e-03,
        8.42702463e-02, -4.52312268e-02, -4.15657312e-02, -5.34140877e-02,
       -8.22660550e-02,  2.05986574e-03, -1.16063096e-01, -9.54612568e-02,
       -3.18644568e-03, -

In [15]:
emb_batch_processing

array([[ 1.3526954e-02, -8.2325451e-02,  5.8019586e-02, ...,
         5.4756008e-02,  6.4687811e-05, -3.1627618e-02],
       [-2.2949705e-02, -1.0813794e-01,  2.7377063e-02, ...,
         2.1301134e-02,  1.2248737e-02, -4.2163379e-02],
       [-4.1390467e-02, -1.1339505e-02, -6.6433256e-03, ...,
         9.4248198e-02,  6.4004302e-02, -2.2237033e-02],
       ...,
       [ 2.4521290e-03, -4.8830509e-02,  5.4585803e-02, ...,
         4.3447401e-02, -7.2111823e-02,  4.1129217e-02],
       [-1.7496713e-02, -7.7107700e-04,  5.4657206e-02, ...,
         3.9128628e-02, -2.5253374e-02, -6.5227404e-02],
       [-7.4132636e-02, -2.8664522e-02, -1.9233793e-02, ...,
        -7.2487772e-02,  1.6280073e-01, -1.9565623e-02]], dtype=float32)

In [16]:
emb_direct_calling

array([ 2.48870794e-02,  1.83277112e-02,  4.77530658e-02, -1.38475662e-02,
        3.02790962e-02, -4.32046838e-02,  6.23071427e-03,  5.95367439e-02,
       -1.12173532e-03, -4.43947613e-02, -1.33559808e-01, -4.43594046e-02,
        1.11916095e-01, -3.71096767e-02,  2.33589225e-02,  7.19019724e-03,
        9.25967693e-02, -3.25391367e-02, -2.97154281e-02, -4.53184731e-02,
        4.93117049e-02,  4.15870920e-02,  7.90585428e-02,  1.44620230e-02,
       -7.66994208e-02, -1.83139148e-03,  4.59219553e-02, -3.48730391e-04,
        6.43289238e-02, -1.70797128e-02,  3.42165120e-02,  5.80768213e-02,
        1.24822510e-02,  6.57148957e-02, -4.90070283e-02,  4.40610908e-02,
       -2.78278813e-02,  4.24919464e-02, -6.80714706e-03, -5.28121889e-02,
       -8.37868154e-02, -6.89068213e-02,  2.37371586e-02, -2.66803242e-03,
        8.42702463e-02, -4.52312268e-02, -4.15657312e-02, -5.34140877e-02,
       -8.22660550e-02,  2.05986574e-03, -1.16063096e-01, -9.54612568e-02,
       -3.18644568e-03, -

In [19]:
from chonkie import SemanticChunker
chunker = SemanticChunker(embeddings_openai, similarity_threshold=0.7)

# Chunk the text
chunks = chunker(text)

In [20]:
chunks

[SemanticChunk(text='\n1. The Evolution of LLM Engineering\n', start_index=0, end_index=37, token_count=10, context=None, sentences=[SemanticSentence(text='\n1.', start_index=0, end_index=3, token_count=3, embedding=array([-0.00796941, -0.00584776, -0.02342363, ..., -0.00952094,
         0.00309695,  0.00754182], dtype=float32)), SemanticSentence(text=' The Evolution of LLM Engineering\n', start_index=3, end_index=37, token_count=7, embedding=array([-0.01866442, -0.00540902, -0.03082924, ...,  0.00124795,
        -0.00084813,  0.01044476], dtype=float32))]),
 SemanticChunk(text='LLM engineering is a cornerstone of modern artificial intelligence, enabling the development and optimization of large language models for diverse applications. These models, like GPT-4 or Gemini, are trained on massive datasets and possess extraordinary capabilities in natural language understanding and generation. However, their true utility lies in how they are engineered to interact with specific tasks and 

##2. Custom Embeddings:

In [22]:
from chonkie.embeddings import BaseEmbeddings
import numpy as np
from typing import List
from transformers import AutoModel, AutoTokenizer


class CustomEmbeddings(BaseEmbeddings):

    def __init__(self):
        # Use a state-of-the-art embedding model
        self.model_name = "intfloat/e5-large-v2"
        self.model = AutoModel.from_pretrained(self.model_name)
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)

    @property
    def dimension(self) -> int:
        """Return the dimensionality of the embeddings."""
        return self.model.config.hidden_size

    def embed(self, text: str) -> "np.ndarray":
        """Generate an embedding for a single text input."""
        inputs = self.tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            padding=True
        )
        outputs = self.model(**inputs)
        embedding = outputs.last_hidden_state.mean(dim=1).detach().numpy()
        return embedding[0]  # Return a 1D numpy array

    def embed_batch(self, texts: List[str]) -> List["np.ndarray"]:
        """Generate embeddings for a batch of text inputs."""
        inputs = self.tokenizer(
            texts,
            return_tensors="pt",
            truncation=True,
            padding=True
        )
        outputs = self.model(**inputs)
        embeddings = outputs.last_hidden_state.mean(dim=1).detach().numpy()
        return [embedding for embedding in embeddings]

    def count_tokens(self, text: str) -> int:
        """Count the number of tokens in a single text input."""
        return len(self.tokenizer.tokenize(text))

    def count_tokens_batch(self, texts: List[str]) -> List[int]:
        """Count the number of tokens for a batch of text inputs."""
        return [len(self.tokenizer.tokenize(text)) for text in texts]

    def get_tokenizer_or_token_counter(self):
        """Return the tokenizer instance."""
        return self.tokenizer

    @classmethod
    def is_available(cls) -> bool:
        """Check if the required dependencies are available."""
        try:
            import transformers
            return True
        except ImportError:
            return False

    def __repr__(self) -> str:
        """String representation of the embedding model."""
        return f"CustomEmbeddings(model_name='{self.model_name}')"

In [23]:
embeddings = CustomEmbeddings()

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

In [24]:
embeddings(texts)

[array([ 0.4359811 , -0.58790463, -0.11468964, ..., -0.7736882 ,
         0.60339296,  0.6033563 ], dtype=float32),
 array([ 0.36218122, -1.1659063 ,  0.56538236, ..., -0.80528873,
         0.8631767 ,  0.66225153], dtype=float32),
 array([ 0.7624157 , -0.9271328 ,  0.8223067 , ..., -0.10036118,
         0.8112479 ,  1.3361131 ], dtype=float32),
 array([ 0.560898  , -0.55373585,  0.05681695, ..., -0.84703386,
         1.0089536 ,  0.93075854], dtype=float32),
 array([-0.2610247 , -1.0300088 , -0.04631982, ..., -0.17331098,
         0.84630984,  0.66522604], dtype=float32),
 array([ 0.18299493, -0.9590812 ,  0.41047063, ..., -0.5811159 ,
         0.83544344,  0.55094576], dtype=float32),
 array([ 0.725686  , -0.63923055,  1.2876815 , ..., -0.7500254 ,
         0.9145995 ,  0.6906319 ], dtype=float32),
 array([ 0.7129024 , -0.2591378 ,  1.2687846 , ..., -0.24357282,
         1.0471714 ,  0.73569274], dtype=float32),
 array([ 0.38317734, -1.1104361 ,  0.51858056, ..., -1.084575  ,
       

In [25]:
from chonkie import SemanticChunker
custom_chunker = SemanticChunker(embeddings, similarity_threshold=0.7)

# Chunk the text
custom_chunks = chunker(text)

In [26]:
custom_chunks

[SemanticChunk(text='\n1. The Evolution of LLM Engineering\n', start_index=0, end_index=37, token_count=10, context=None, sentences=[SemanticSentence(text='\n1.', start_index=0, end_index=3, token_count=3, embedding=array([-0.0079946 , -0.00584424, -0.02344213, ..., -0.00952184,
         0.00310335,  0.00753846], dtype=float32)), SemanticSentence(text=' The Evolution of LLM Engineering\n', start_index=3, end_index=37, token_count=7, embedding=array([-0.01877389, -0.00547267, -0.03072889, ...,  0.00133158,
        -0.00083864,  0.01038929], dtype=float32))]),
 SemanticChunk(text='LLM engineering is a cornerstone of modern artificial intelligence, enabling the development and optimization of large language models for diverse applications. These models, like GPT-4 or Gemini, are trained on massive datasets and possess extraordinary capabilities in natural language understanding and generation. However, their true utility lies in how they are engineered to interact with specific tasks and 